openapi: 3.0.0
info:
  version: 1.0.0
  title: CERN Analysis Preservation REST API
  termsOfService: 'https://analysispreservation.cern.ch/terms/'
  contact:
    email: analysis-preservation-support@cern.ch
    url: 'https://analysispreservation.cern.ch/about'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: >-
      https://github.com/cernanalysispreservation/cap-api-docs/raw/master/web/CAP_API_docs.png
  description: >
    CERN Analysis Preservation offers a REST API to access the service
    independently from the web interface. If you want to automate specific tasks
    or create your own data interface, you can use the API to do so


    # Introduction

    The CAP API is built on HTTP. Our API is RESTful. It has predictable
    resource URLs. It returns HTTP response codes to indicate errors. It also
    accepts and returns JSON in the HTTP body. You can use your favorite
    HTTP/REST library for your programming language to use CAP's API, or you can
    use one of our SDKs (CLI clients) (currently available in Python).


    We have other APIs that are also available. Every action from our app is
    supported by an API which is documented and available for use so that you
    may automate any workflows necessary. This document contains the most
    commonly integrated resources.


    # Authentication

    If you want to gain access to CERN Analysis Preservation from your console
    or any external means other

    than the web portal you will need an access token to authenticate with the
    portal. You can create

    multiple tokens for different services.


    CAP offers the following forms of authentication:
      - API Key - `access_token`

    <!-- ReDoc-Inject: <security-definitions> -->
externalDocs:
  description: Click here if you are looking for our developement documentation.
  url: 'https://cernanalysispreservation.readthedocs.io'
tags:
  - name: Deposits
    description: The Deposit resource is used for uploading and editing records on CAP
  - name: Records
    description: >
      The Record resource is used for fetching and searching published records
      on CAP. Create deposit
  - name: Files
    description: >
      The Files resource is used for uploading files and attach them to
      records/deposits

      The following type of upload are possible:
        * Local files
        * Git repos
        * URL linked files
  - name: User
    description: Operations about user
  - name: Services
    description: Operations about services
  - name: Schemas
    description: Operations about schemas
security:
  - Access Token: []
servers:
  - url: 'http://localhost:5000'
  - url: 'https://analysispreservation.cern.ch/api'
  - url: 'https://analysispreservation-dev.cern.ch/api'
