get:
  summary: Get list of services
  tags:
    - Services
  responses:
    '200':
      description: OK
      headers:
        X-Rate-Limit:
          $ref: '#/components/headers/RateLimit'
        X-Expires-After:
          $ref: '#/components/headers/ExpiresAfter'
      content:
        application/json:
          schema:
            type: string
          examples:
            response:
              value: Hello world!
